"""
Lathe App Artifacts

Plain data objects representing execution results.
These are the "nouns" of the app layer.
"""
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional


def _generate_id() -> str:
    """Generate a unique artifact ID."""
    return str(uuid.uuid4())


def _now() -> str:
    """Generate ISO timestamp."""
    return datetime.now(timezone.utc).isoformat()


@dataclass
class ArtifactInput:
    """The input that produced an artifact."""
    intent: str
    task: str
    why: Dict[str, Any]
    model_requested: Optional[str] = None
    workspace_id: Optional[str] = None


@dataclass
class ObservabilityTrace:
    """Observability data from pipeline execution."""
    trace_id: str
    stages: List[Dict[str, Any]]
    models: Dict[str, Any]
    outcome: Dict[str, Any]
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "ObservabilityTrace":
        """Create from pipeline _observability block."""
        return cls(
            trace_id=data.get("trace_id", ""),
            stages=data.get("stages", []),
            models=data.get("models", {}),
            outcome=data.get("outcome", {}),
        )
    
    @classmethod
    def empty(cls) -> "ObservabilityTrace":
        """Create an empty trace."""
        return cls(trace_id="", stages=[], models={}, outcome={})


@dataclass
class RefusalArtifact:
    """
    Represents a refusal from Lathe.
    
    A refusal is NOT a failure - it's a valid outcome
    indicating the request could not be fulfilled.
    """
    id: str
    timestamp: str
    input: ArtifactInput
    reason: str
    details: str
    observability: ObservabilityTrace
    
    @classmethod
    def create(
        cls,
        input_data: ArtifactInput,
        reason: str,
        details: str,
        observability: ObservabilityTrace,
    ) -> "RefusalArtifact":
        return cls(
            id=_generate_id(),
            timestamp=_now(),
            input=input_data,
            reason=reason,
            details=details,
            observability=observability,
        )


@dataclass
class ProposalArtifact:
    """
    Represents a successful proposal from Lathe.
    
    Contains the proposals, assumptions, and risks
    generated by the model.
    """
    id: str
    timestamp: str
    input: ArtifactInput
    proposals: List[Dict[str, Any]]
    assumptions: List[str]
    risks: List[str]
    results: List[Any]
    model_fingerprint: Optional[str]
    observability: ObservabilityTrace
    
    @classmethod
    def create(
        cls,
        input_data: ArtifactInput,
        proposals: List[Dict[str, Any]],
        assumptions: List[str],
        risks: List[str],
        results: List[Any],
        model_fingerprint: Optional[str],
        observability: ObservabilityTrace,
    ) -> "ProposalArtifact":
        return cls(
            id=_generate_id(),
            timestamp=_now(),
            input=input_data,
            proposals=proposals,
            assumptions=assumptions,
            risks=risks,
            results=results,
            model_fingerprint=model_fingerprint,
            observability=observability,
        )


@dataclass
class PlanArtifact:
    """
    Represents a plan generated by Lathe.
    
    Plans are structured sequences of steps
    that can be executed or reviewed.
    """
    id: str
    timestamp: str
    input: ArtifactInput
    steps: List[Dict[str, Any]]
    dependencies: List[str]
    results: List[Any]
    model_fingerprint: Optional[str]
    observability: ObservabilityTrace
    
    @classmethod
    def create(
        cls,
        input_data: ArtifactInput,
        steps: List[Dict[str, Any]],
        dependencies: List[str],
        results: List[Any],
        model_fingerprint: Optional[str],
        observability: ObservabilityTrace,
    ) -> "PlanArtifact":
        return cls(
            id=_generate_id(),
            timestamp=_now(),
            input=input_data,
            steps=steps,
            dependencies=dependencies,
            results=results,
            model_fingerprint=model_fingerprint,
            observability=observability,
        )


@dataclass
class RunRecord:
    """
    Complete record of a single orchestrator execution.
    
    This is the top-level artifact returned by run_request().
    Contains the input, output artifact, and execution metadata.
    """
    id: str
    timestamp: str
    input: ArtifactInput
    output: Any  # RefusalArtifact | ProposalArtifact | PlanArtifact
    model_used: str
    fallback_triggered: bool
    success: bool
    classification: Any = None  # ResultClassification
    escalation: Optional[Dict[str, Any]] = None
    
    @classmethod
    def create(
        cls,
        input_data: ArtifactInput,
        output: Any,
        model_used: str,
        fallback_triggered: bool,
        success: bool,
        classification: Any = None,
        escalation: Optional[Dict[str, Any]] = None,
    ) -> "RunRecord":
        return cls(
            id=_generate_id(),
            timestamp=_now(),
            input=input_data,
            output=output,
            model_used=model_used,
            fallback_triggered=fallback_triggered,
            success=success,
            classification=classification,
            escalation=escalation,
        )
